name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run release # Adjust this command to match your build script

    - name: Prepare deployment directory
      run: |
        mkdir -p deployment/js
        cp -r resources/public/* deployment/
        cp target/app/js/main.js deployment/js/

    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: deployment

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
